# Site
title: ShubhamJain.in
author: SHUBHAM JAIN
description: >
        This is my online home, Here I post my projects, code, blogs and anything else.
url: https://www.shubhamjain.in
logo: logo.png                            # Site logo
home: home.png
locale: en_US
excerpt_separator: <!-- more -->

assets:
  compress:
    css: true
    js: true

# Left Block Images
background:
  about: assets/images/backgrounds/about.jpg

# Jekyll
permalink: /:categories/:year/:month/:day/:title
future: true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:            GFM
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics:   UA-84199733-1


# Disqus
disqus_shortname: "shubhamjain-in"
comments: true

# Social Links
email:  mail@shubhamjain.in
linkedin:  shubm
#keybase: ishubham
github:  "shubm"
# bitbucket: ishubham
# stackoverflow:  6476326/shubham-jain
twitter:  "aweshm_"
messenger: always.awesom

#Tips' links
#btc:
#paypal:


# Gems plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, script, _posts/archive, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, Makefile, .sass-cache, .DS_Store, script, .travis.yml, assets/search.html]
